# Generated by Django 5.0.3 on 2024-04-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name="Data dell'Evento")),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Obiettivo')),
                ('value', models.TextField(verbose_name='Valore')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='hqmanager.event')),
            ],
        ),
    ]
